# Generated by Django 3.1.4 on 2021-04-02 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0003_auto_20210402_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(max_length=30)),
                ('form_factor', models.TextField(max_length=30)),
                ('memory', models.TextField(max_length=30)),
                ('buffer', models.TextField(max_length=30)),
                ('freq', models.TextField(max_length=30)),
                ('interface', models.TextField(max_length=30)),
                ('propusk_sposob', models.TextField(max_length=30)),
                ('power', models.TextField(max_length=30)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.brand')),
            ],
        ),
    ]
