# Generated by Django 3.1.4 on 2021-04-02 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0004_hdd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(max_length=30)),
                ('work_freq', models.TextField(max_length=30)),
                ('ddr3', models.TextField(max_length=30)),
                ('ddr4', models.TextField(max_length=30)),
                ('pcie1', models.TextField(max_length=30)),
                ('pcie8', models.TextField(max_length=30)),
                ('pcie16', models.TextField(max_length=30)),
                ('port', models.TextField(max_length=150)),
                ('bios', models.TextField(max_length=30)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.brand')),
                ('chipsetA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.coreamd')),
                ('chipsetI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.chipsetintel')),
                ('form_fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.formfactormother')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.socketmother')),
            ],
        ),
    ]
