# Generated by Django 3.1.4 on 2021-04-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0007_auto_20210402_1626'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RAM',
        ),
    ]
