# Generated by Django 3.1.4 on 2021-04-02 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0010_auto_20210402_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(max_length=30)),
                ('tech_proc', models.TextField(max_length=30)),
                ('series', models.TextField(max_length=30)),
                ('graph_proc', models.TextField(max_length=30)),
                ('freq_proc', models.TextField(max_length=30)),
                ('threading', models.TextField(max_length=30)),
                ('type_memory', models.TextField(max_length=30)),
                ('size_shina_video', models.TextField(max_length=30)),
                ('freq_videomemory', models.TextField(max_length=30)),
                ('api', models.TextField(max_length=30)),
                ('connector', models.TextField(max_length=30)),
                ('port', models.TextField(max_length=30)),
                ('added_power', models.TextField(max_length=30)),
                ('power', models.TextField(max_length=30)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.brand')),
            ],
        ),
    ]
