# Generated by Django 3.1.4 on 2021-04-03 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0012_powersupply'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField(max_length=30)),
                ('type_mem', models.TextField(max_length=30)),
                ('memory', models.TextField(max_length=30)),
                ('speed_read', models.TextField(max_length=30)),
                ('speed_write', models.TextField(max_length=30)),
                ('interface', models.TextField(max_length=30)),
                ('propusk_sposob', models.TextField(max_length=30)),
                ('power_in', models.TextField(max_length=30)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.brand')),
                ('form_factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.formfactorssd')),
            ],
        ),
    ]
