# Generated by Django 3.2.2 on 2021-05-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0017_auto_20210520_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=40)),
                ('content', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='UsersComputer',
        ),
    ]
