# Generated by Django 3.2.2 on 2021-05-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0018_auto_20210523_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(max_length=900),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
