# Generated by Django 3.2.2 on 2021-06-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0019_auto_20210524_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='mother',
            name='has_NVMe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mother',
            name='m2_cnt',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='mother',
            name='mini_sata_cnt',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='mother',
            name='pcie4',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='mother',
            name='sata_cnt',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
