# Generated by Django 3.2.2 on 2021-06-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0020_auto_20210615_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mother',
            name='m2_cnt',
            field=models.IntegerField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mother',
            name='mini_sata_cnt',
            field=models.IntegerField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mother',
            name='sata_cnt',
            field=models.IntegerField(blank=True, max_length=30),
        ),
    ]
