# Generated by Django 3.2.2 on 2021-06-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0021_auto_20210615_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mother',
            name='mini_sata_cnt',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='pcie1',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='pcie4',
        ),
        migrations.RemoveField(
            model_name='mother',
            name='pcie8',
        ),
        migrations.AddField(
            model_name='mother',
            name='ddr3L',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mother',
            name='m2_cnt',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='sata_cnt',
            field=models.IntegerField(blank=True),
        ),
    ]
