# Generated by Django 3.2.2 on 2021-06-21 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0024_cabinet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='bug_hdd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hardware.hdd'),
        ),
    ]
