# Generated by Django 3.2.2 on 2021-07-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0028_computer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabinet',
            name='bug_cpu',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='bug_mother',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cabinet',
            name='bug_video',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
