# Generated by Django 3.2.2 on 2021-07-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0030_auto_20210710_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='bag_powersup',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='bag_ram',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='bag_ssd',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
