# Generated by Django 3.2.2 on 2021-07-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0031_auto_20210710_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='hdd_id',
            new_name='cpu_ids',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='mother_id',
            new_name='hdd_ids',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='power_supply_id',
            new_name='mother_ids',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='cpu_id',
        ),
        migrations.AddField(
            model_name='computer',
            name='power_supply_ids',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='computer',
            name='ram_ids',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='computer',
            name='ssd_ids',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='computer',
            name='video_ids',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
