# Generated by Django 3.2.2 on 2021-07-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0032_auto_20210716_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceMemory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mother',
            name='pcie2',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='mother',
            name='pcie4',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mother',
            name='pcie16',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
