# Generated by Django 3.2.2 on 2021-08-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0035_computer_type_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='type_item',
        ),
        migrations.AddField(
            model_name='hdd',
            name='type_item',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='hardware.typeitem'),
        ),
        migrations.AddField(
            model_name='mother',
            name='type_item',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='hardware.typeitem'),
        ),
        migrations.AddField(
            model_name='powersupply',
            name='type_item',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='hardware.typeitem'),
        ),
        migrations.AddField(
            model_name='processor',
            name='type_item',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='hardware.typeitem'),
        ),
        migrations.AddField(
            model_name='ram',
            name='type_item',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='hardware.typeitem'),
        ),
        migrations.AddField(
            model_name='ssd',
            name='type_item',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='hardware.typeitem'),
        ),
        migrations.AddField(
            model_name='videocard',
            name='type_item',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='hardware.typeitem'),
        ),
    ]
