# Generated by Django 3.2.2 on 2021-08-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0038_auto_20210821_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mother',
            name='cpu',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mother',
            name='ddr3',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mother',
            name='ddr3L',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mother',
            name='ddr4',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mother',
            name='pcie16',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mother',
            name='pcie2',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mother',
            name='pcie4',
            field=models.TextField(blank=True, max_length=30),
        ),
    ]
