# Generated by Django 3.2.2 on 2021-08-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0039_auto_20210821_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='mother',
            name='msata_cnt',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
