# Generated by Django 3.2.2 on 2021-09-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0041_auto_20210821_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='mother',
            name='power',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='processor',
            name='power',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='ram',
            name='power',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='ssd',
            name='power',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='power',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='mother',
            name='cpu',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='ddr3',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='ddr3L',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='ddr4',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='pcie16',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='pcie2',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='mother',
            name='pcie4',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='power',
            field=models.IntegerField(default=230),
        ),
    ]
