# Generated by Django 3.2.2 on 2021-09-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0042_auto_20210906_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdd',
            name='power_interface',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='videocard',
            name='power_interface',
            field=models.TextField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='power',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='mother',
            name='power',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='processor',
            name='power',
            field=models.IntegerField(default=130),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='power',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='power',
            field=models.IntegerField(default=200),
        ),
    ]
