# Generated by Django 3.2.2 on 2021-10-09 09:52

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hardware', '0043_auto_20210906_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWrap',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('telephone', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='hdd',
            name='power',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='mother',
            name='power',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='processor',
            name='power',
            field=models.IntegerField(default=125),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='power',
            field=models.IntegerField(default=5),
        ),
    ]
