# Generated by Django 3.2.2 on 2021-10-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardware', '0044_auto_20211009_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwrap',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hdd',
            name='power',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='mother',
            name='power',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='processor',
            name='power',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='ram',
            name='power',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='power',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='videocard',
            name='power',
            field=models.IntegerField(default=250),
        ),
    ]
